import type {
  AirlessRockyBodyArtifact,
  BodyGenerationFidelity,
  BodyGenerationLifecycle,
  BodyGenerationLifecycleStatus,
  BodyGenerationProfile,
  BodyGenerationRecord,
  GeneratedSystemBodyArtifact,
  SystemOrbitalContextArtifact,
  WorldProject
} from '@world-forge/shared';
import {
  airlessRockyBodyArtifactKey,
  airlessRockyBodySourceFromProject,
  isCurrentAirlessRockyBodyArtifact
} from './airlessRockyBody';
import {
  SYSTEM_BODY_GENERATION_WORKFLOW_ID,
  SYSTEM_BODY_GENERATION_WORKFLOW_VERSION,
  isCurrentGeneratedSystemBodyArtifact,
  resolveSystemBodyProfile,
  systemBodyArtifactKey,
  systemBodyGenerationGraphSignature,
  systemBodyGenerationSourceFromProject,
  systemBodyGenerationSourceSignature,
  systemBodyGenerationWorkflowDescriptor
} from './systemBodyGeneration';

export const BODY_GENERATION_LIFECYCLE_VERSION = 'body-generation-lifecycle-v1' as const;

export function reconcileBodyGenerationLifecycle(
  project: WorldProject,
  orbitalContext: SystemOrbitalContextArtifact,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const existing = project.bodyGeneration;
  const records: Record<string, BodyGenerationRecord> = {};
  const starId = orbitalContext.payload.star.id;
  const primaryId = orbitalContext.payload.primaryBodyId;

  records[starId] = reconcileRecord({
    existing: existing?.records[starId],
    bodyId: starId,
    parentBodyId: null,
    status: 'generated',
    eligible: false,
    eligibilityReason: 'The star uses its dedicated stellar-surface presentation workflow.',
    profile: null,
    stableSeed: `${project.seed}:body:${starId}:generated`,
    sourceBodySignature: orbitalContext.artifactSignature,
    workflow: existing?.records[starId]?.workflow ?? { id: '', version: '', graphSignature: undefined },
    nowIso
  });

  for (const body of orbitalContext.payload.bodies) {
    const isPrimary = body.id === primaryId;
    const profile = isPrimary ? null : resolveSystemBodyProfile(body);
    const requestedFidelity = existing?.records[body.id]?.requestedFidelity ?? 'preview';
    const source = profile
      ? systemBodyGenerationSourceFromProject(project, orbitalContext, body.id, requestedFidelity)
      : null;
    const sourceBodySignature = source
      ? systemBodyGenerationSourceSignature(source)
      : stableSignature({ orbitalArtifactSignature: orbitalContext.artifactSignature, body });
    const artifact = source ? project.enrichmentArtifacts?.[systemBodyArtifactKey(body.id)] : undefined;
    const currentArtifact = source && isCurrentGeneratedSystemBodyArtifact(source, artifact)
      ? artifact
      : null;
    const fallbackArtifact = source
      ? currentGeneratedBodyArtifactForAnyFidelity(project, orbitalContext, body.id, artifact)
      : null;
    const usableArtifact = currentArtifact ?? fallbackArtifact;
    const staleArtifact = Boolean(source && artifact && !usableArtifact);
    const status: BodyGenerationLifecycleStatus = isPrimary
      ? 'generated'
      : usableArtifact
        ? 'generated'
        : staleArtifact
          ? 'stale'
          : 'ready';
    const workflow = profile
      ? {
          id: SYSTEM_BODY_GENERATION_WORKFLOW_ID,
          version: SYSTEM_BODY_GENERATION_WORKFLOW_VERSION,
          graphSignature: systemBodyGenerationGraphSignature(profile)
        }
      : existing?.records[body.id]?.workflow ?? { id: '', version: '', graphSignature: undefined };

    records[body.id] = reconcileRecord({
      existing: existing?.records[body.id],
      bodyId: body.id,
      parentBodyId: body.parentBodyId,
      status,
      eligible: !isPrimary,
      eligibilityReason: isPrimary
        ? 'The primary world is generated by the ordinary world workflow.'
        : `Eligible for the capability-resolved ${formatProfile(profile as BodyGenerationProfile)} workflow.`,
      profile,
      stableSeed: source?.seed ?? `${project.seed}:body:${body.id}:generated`,
      sourceBodySignature,
      requestedFidelity,
      workflow,
      nowIso,
      artifactKey: usableArtifact?.artifactKey,
      completedAt: usableArtifact?.completedAt,
      staleReason: staleArtifact
        ? 'Saved generated-body artifact no longer matches the current project, orbital artifact, workflow graph, or body profile.'
        : undefined
    });
  }

  const queue = (existing?.queue ?? []).filter((bodyId) => records[bodyId]?.status === 'queued');
  const activeBodyId = existing?.activeBodyId && records[existing.activeBodyId]?.status === 'generating'
    ? existing.activeBodyId
    : null;
  const normalized = {
    modelVersion: BODY_GENERATION_LIFECYCLE_VERSION,
    executionMode: 'sequential' as const,
    queue,
    activeBodyId,
    paused: existing?.paused ?? true,
    updatedAt: existing?.updatedAt ?? nowIso,
    records
  } satisfies BodyGenerationLifecycle;
  return lifecycleEquals(existing, normalized) ? existing as BodyGenerationLifecycle : normalized;
}

export function queueBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  requestedFidelity: BodyGenerationFidelity = 'preview',
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record?.eligible || record.status === 'generating' || record.status === 'queued') return lifecycle;
  const queue = lifecycle.queue.includes(bodyId) ? lifecycle.queue : [...lifecycle.queue, bodyId];
  return updateLifecycle(lifecycle, {
    queue,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: 'queued',
        requestedFidelity,
        requestedAt: nowIso,
        startedAt: undefined,
        failureReason: undefined,
        staleReason: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function queueUnresolvedBodies(
  lifecycle: BodyGenerationLifecycle,
  requestedFidelity: BodyGenerationFidelity = 'preview',
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  let next = lifecycle;
  for (const record of Object.values(lifecycle.records)) {
    if (!record.eligible || record.status === 'generated' || record.status === 'generating' || record.status === 'queued') continue;
    next = queueBodyGeneration(next, record.bodyId, requestedFidelity, nowIso);
  }
  return next;
}

export function queueBackgroundPreviewBodies(
  lifecycle: BodyGenerationLifecycle,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  let next = lifecycle;
  for (const record of Object.values(lifecycle.records)) {
    if (!record.eligible || (record.status !== 'ready' && record.status !== 'placeholder') || record.artifactKeys.length > 0) continue;
    next = queueBodyGeneration(next, record.bodyId, 'preview', nowIso);
  }
  return next;
}

export function queueUnresolvedAirlessMoons(
  lifecycle: BodyGenerationLifecycle,
  requestedFidelity: BodyGenerationFidelity = 'preview',
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  return queueUnresolvedBodies(lifecycle, requestedFidelity, nowIso);
}

export function startNextBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  if (lifecycle.activeBodyId || lifecycle.paused || lifecycle.queue.length === 0) return lifecycle;
  const bodyId = lifecycle.queue[0];
  const record = lifecycle.records[bodyId];
  if (!record || record.status !== 'queued') {
    return updateLifecycle(lifecycle, { queue: lifecycle.queue.slice(1) }, nowIso);
  }
  return updateLifecycle(lifecycle, {
    queue: lifecycle.queue.slice(1),
    activeBodyId: bodyId,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: 'generating',
        startedAt: nowIso,
        failureReason: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function resumeBodyGenerationQueue(
  lifecycle: BodyGenerationLifecycle,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  return updateLifecycle(lifecycle, { paused: false }, nowIso);
}

export function pauseBodyGenerationQueue(
  lifecycle: BodyGenerationLifecycle,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  return updateLifecycle(lifecycle, { paused: true }, nowIso);
}

export function preemptActiveBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record || lifecycle.activeBodyId !== bodyId || record.status !== 'generating') return lifecycle;
  return updateLifecycle(lifecycle, {
    queue: [bodyId, ...lifecycle.queue.filter((candidate) => candidate !== bodyId)],
    activeBodyId: null,
    paused: true,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: 'queued',
        startedAt: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function removeQueuedBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record || record.status !== 'queued') return lifecycle;
  return updateLifecycle(lifecycle, {
    queue: lifecycle.queue.filter((candidate) => candidate !== bodyId),
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: fallbackReadyStatus(record),
        requestedAt: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function cancelActiveBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record || lifecycle.activeBodyId !== bodyId || record.status !== 'generating') return lifecycle;
  return updateLifecycle(lifecycle, {
    activeBodyId: null,
    paused: true,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: fallbackReadyStatus(record),
        startedAt: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function failBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  failureReason: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record) return lifecycle;
  return updateLifecycle(lifecycle, {
    activeBodyId: lifecycle.activeBodyId === bodyId ? null : lifecycle.activeBodyId,
    paused: true,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: 'failed',
        failureReason,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function completeBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  artifact: GeneratedSystemBodyArtifact | AirlessRockyBodyArtifact,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[artifact.bodyId];
  if (!record) return lifecycle;
  return updateLifecycle(lifecycle, {
    activeBodyId: lifecycle.activeBodyId === artifact.bodyId ? null : lifecycle.activeBodyId,
    records: {
      ...lifecycle.records,
      [artifact.bodyId]: {
        ...record,
        status: 'generated',
        requestedFidelity: 'requestedFidelity' in artifact ? artifact.requestedFidelity : record.requestedFidelity,
        workflow: {
          id: artifact.workflow.id,
          version: artifact.workflow.version,
          graphSignature: artifact.workflow.graphSignature
        },
        sourceBodySignature: artifact.source.sourceSignature,
        artifactKeys: [...new Set([...record.artifactKeys, artifact.artifactKey])],
        completedAt: artifact.completedAt,
        failureReason: undefined,
        staleReason: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function retryBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record || (record.status !== 'failed' && record.status !== 'stale')) return lifecycle;
  return queueBodyGeneration(lifecycle, bodyId, record.requestedFidelity, nowIso);
}

export function bodyArtifactForBody(
  project: WorldProject,
  orbitalContext: SystemOrbitalContextArtifact,
  bodyId: string,
  requestedFidelity: BodyGenerationFidelity = 'preview'
): GeneratedSystemBodyArtifact | null {
  try {
    const source = systemBodyGenerationSourceFromProject(project, orbitalContext, bodyId, requestedFidelity);
    const artifact = project.enrichmentArtifacts?.[systemBodyArtifactKey(bodyId)];
    if (isCurrentGeneratedSystemBodyArtifact(source, artifact)) return artifact;
    return currentGeneratedBodyArtifactForAnyFidelity(project, orbitalContext, bodyId, artifact);
  } catch {
    return null;
  }
}

export function airlessArtifactForBody(
  project: WorldProject,
  orbitalContext: SystemOrbitalContextArtifact,
  bodyId: string,
  requestedFidelity: BodyGenerationFidelity = 'preview'
): AirlessRockyBodyArtifact | null {
  try {
    const source = airlessRockyBodySourceFromProject(project, orbitalContext, bodyId, requestedFidelity);
    const artifact = project.enrichmentArtifacts?.[airlessRockyBodyArtifactKey(bodyId)];
    return isCurrentAirlessRockyBodyArtifact(source, artifact) ? artifact : null;
  } catch {
    return null;
  }
}

function currentGeneratedBodyArtifactForAnyFidelity(
  project: WorldProject,
  orbitalContext: SystemOrbitalContextArtifact,
  bodyId: string,
  artifact: unknown
): GeneratedSystemBodyArtifact | null {
  if (!artifact || typeof artifact !== 'object') return null;
  const candidate = artifact as Partial<GeneratedSystemBodyArtifact>;
  if (candidate.requestedFidelity !== 'preview' && candidate.requestedFidelity !== 'standard') return null;
  try {
    const source = systemBodyGenerationSourceFromProject(project, orbitalContext, bodyId, candidate.requestedFidelity);
    return isCurrentGeneratedSystemBodyArtifact(source, artifact) ? artifact as GeneratedSystemBodyArtifact : null;
  } catch {
    return null;
  }
}

function reconcileRecord(input: {
  existing: BodyGenerationRecord | undefined;
  bodyId: string;
  parentBodyId: string | null;
  status: BodyGenerationLifecycleStatus;
  eligible: boolean;
  eligibilityReason: string;
  profile: BodyGenerationRecord['profile'];
  stableSeed: string;
  sourceBodySignature: string;
  requestedFidelity?: BodyGenerationFidelity;
  workflow: BodyGenerationRecord['workflow'];
  nowIso: string;
  artifactKey?: string;
  completedAt?: string;
  staleReason?: string;
}): BodyGenerationRecord {
  const existing = input.existing;
  const sourceChanged = Boolean(existing && existing.sourceBodySignature !== input.sourceBodySignature);
  const preserveQueuedUpgrade = Boolean(
    sourceChanged
    && input.artifactKey
    && existing
    && (existing.status === 'queued' || existing.status === 'generating')
  );
  const preservedStatus = existing && input.eligible
    && ['queued', 'generating', 'failed'].includes(existing.status)
    && (!sourceChanged || preserveQueuedUpgrade)
    ? existing.status
    : input.status;
  const artifactKeys = input.artifactKey
    ? [...new Set([...(existing?.artifactKeys ?? []), input.artifactKey])]
    : existing?.artifactKeys ?? [];
  return {
    bodyId: input.bodyId,
    parentBodyId: input.parentBodyId,
    status: sourceChanged && existing?.status === 'generated' && !input.artifactKey ? 'stale' : preservedStatus,
    eligible: input.eligible,
    eligibilityReason: input.eligibilityReason,
    profile: input.profile,
    stableSeed: input.stableSeed,
    requestedFidelity: input.requestedFidelity ?? existing?.requestedFidelity ?? 'preview',
    workflow: input.workflow,
    sourceBodySignature: input.sourceBodySignature,
    artifactKeys,
    requestedAt: preservedStatus === 'queued' || preservedStatus === 'generating' ? existing?.requestedAt : undefined,
    startedAt: preservedStatus === 'generating' ? existing?.startedAt : undefined,
    completedAt: input.status === 'generated' ? input.completedAt ?? existing?.completedAt : undefined,
    updatedAt: existing?.updatedAt ?? input.nowIso,
    staleReason: sourceChanged && !input.artifactKey ? 'Body scaffold or orbital source changed after generation.' : input.staleReason,
    failureReason: preservedStatus === 'failed' ? existing?.failureReason : undefined
  };
}

function fallbackReadyStatus(record: BodyGenerationRecord): BodyGenerationLifecycleStatus {
  if (record.artifactKeys.length > 0) return 'generated';
  return record.eligible ? 'ready' : 'placeholder';
}

function updateLifecycle(
  lifecycle: BodyGenerationLifecycle,
  changes: Partial<BodyGenerationLifecycle>,
  nowIso: string
): BodyGenerationLifecycle {
  return {
    ...lifecycle,
    ...changes,
    updatedAt: nowIso
  };
}

function lifecycleEquals(left: BodyGenerationLifecycle | undefined, right: BodyGenerationLifecycle): boolean {
  if (!left) return false;
  return JSON.stringify(left) === JSON.stringify(right);
}

function formatProfile(profile: BodyGenerationProfile): string {
  return profile.split('-').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
}

function stableSignature(value: unknown): string {
  const serialized = stableStringify(value);
  let hash = 2166136261;
  for (let index = 0; index < serialized.length; index += 1) {
    hash ^= serialized.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return `fnv1a-${(hash >>> 0).toString(16).padStart(8, '0')}`;
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(record[key])}`).join(',')}}`;
  }
  return JSON.stringify(value);
}
