import type {
  AirlessRockyBodyArtifact,
  BodyGenerationFidelity,
  BodyGenerationLifecycle,
  BodyGenerationRecord,
  BodyGenerationLifecycleStatus,
  SystemOrbitalContextArtifact,
  WorldProject
} from '@world-forge/shared';
import {
  AIRLESS_ROCKY_BODY_PROFILE,
  AIRLESS_ROCKY_BODY_WORKFLOW_ID,
  AIRLESS_ROCKY_BODY_WORKFLOW_VERSION,
  airlessRockyBodyArtifactKey,
  airlessRockyBodyGraphSignature,
  airlessRockyBodySourceFromProject,
  airlessRockyBodySourceSignature,
  isCurrentAirlessRockyBodyArtifact
} from './airlessRockyBody';

export const BODY_GENERATION_LIFECYCLE_VERSION = 'body-generation-lifecycle-v1' as const;

export function reconcileBodyGenerationLifecycle(
  project: WorldProject,
  orbitalContext: SystemOrbitalContextArtifact,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const existing = project.bodyGeneration;
  const records: Record<string, BodyGenerationRecord> = {};
  const starId = orbitalContext.payload.star.id;
  const primaryId = orbitalContext.payload.primaryBodyId;

  records[starId] = reconcileRecord({
    existing: existing?.records[starId],
    bodyId: starId,
    parentBodyId: null,
    status: 'generated',
    eligible: false,
    eligibilityReason: 'The generated star is not a secondary-body workflow target.',
    profile: null,
    stableSeed: `${project.seed}:body:${starId}:generated`,
    sourceBodySignature: orbitalContext.artifactSignature,
    nowIso
  });

  for (const body of orbitalContext.payload.bodies) {
    const isPrimary = body.id === primaryId;
    const isEligibleMoon = body.kind === 'moon' && !isPrimary && body.placeholder;
    const source = isEligibleMoon
      ? airlessRockyBodySourceFromProject(project, orbitalContext, body.id, existing?.records[body.id]?.requestedFidelity ?? 'preview')
      : null;
    const sourceBodySignature = source
      ? airlessRockyBodySourceSignature(source)
      : stableSignature({ orbitalArtifactSignature: orbitalContext.artifactSignature, body });
    const artifactKey = source ? airlessRockyBodyArtifactKey(body.id) : '';
    const artifact = artifactKey ? project.enrichmentArtifacts?.[artifactKey] : undefined;
    const currentArtifact = source && isCurrentAirlessRockyBodyArtifact(source, artifact)
      ? artifact
      : null;
    const staleArtifact = source && artifact && !currentArtifact;
    const defaultStatus: BodyGenerationLifecycleStatus = isPrimary || !body.placeholder
      ? 'generated'
      : isEligibleMoon
        ? 'ready'
        : 'placeholder';
    const eligible = isEligibleMoon;
    const eligibilityReason = isPrimary
      ? 'The primary world is generated by the ordinary world workflow.'
      : isEligibleMoon
        ? 'Eligible for the bounded airless rocky moon workflow.'
        : 'This body profile is not supported by the first secondary-body proof.';
    const requestedFidelity = existing?.records[body.id]?.requestedFidelity ?? 'preview';
    const baseRecord = reconcileRecord({
      existing: existing?.records[body.id],
      bodyId: body.id,
      parentBodyId: body.parentBodyId,
      status: currentArtifact ? 'generated' : staleArtifact ? 'stale' : defaultStatus,
      eligible,
      eligibilityReason,
      profile: eligible ? AIRLESS_ROCKY_BODY_PROFILE : null,
      stableSeed: source?.seed ?? `${project.seed}:body:${body.id}:generated`,
      sourceBodySignature,
      requestedFidelity,
      nowIso,
      artifactKey: currentArtifact?.artifactKey,
      completedAt: currentArtifact?.completedAt,
      staleReason: staleArtifact ? 'Saved generated-body artifact no longer matches the current project, orbital artifact, workflow, or requested fidelity.' : undefined
    });
    records[body.id] = baseRecord;
  }

  const queue = (existing?.queue ?? []).filter((bodyId) => records[bodyId]?.status === 'queued');
  const activeBodyId = existing?.activeBodyId && records[existing.activeBodyId]?.status === 'generating'
    ? existing.activeBodyId
    : null;
  const normalized = {
    modelVersion: BODY_GENERATION_LIFECYCLE_VERSION,
    executionMode: 'sequential' as const,
    queue,
    activeBodyId,
    paused: existing?.paused ?? true,
    updatedAt: existing?.updatedAt ?? nowIso,
    records
  } satisfies BodyGenerationLifecycle;
  return lifecycleEquals(existing, normalized) ? existing as BodyGenerationLifecycle : normalized;
}

export function queueBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  requestedFidelity: BodyGenerationFidelity = 'preview',
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record?.eligible || record.status === 'generating' || record.status === 'queued') return lifecycle;
  const queue = lifecycle.queue.includes(bodyId) ? lifecycle.queue : [...lifecycle.queue, bodyId];
  return updateLifecycle(lifecycle, {
    queue,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: 'queued',
        requestedFidelity,
        requestedAt: nowIso,
        startedAt: undefined,
        failureReason: undefined,
        staleReason: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function queueUnresolvedAirlessMoons(
  lifecycle: BodyGenerationLifecycle,
  requestedFidelity: BodyGenerationFidelity = 'preview',
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  let next = lifecycle;
  for (const record of Object.values(lifecycle.records)) {
    if (!record.eligible || record.status === 'generated' || record.status === 'generating' || record.status === 'queued') continue;
    next = queueBodyGeneration(next, record.bodyId, requestedFidelity, nowIso);
  }
  return next;
}

export function startNextBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  if (lifecycle.activeBodyId || lifecycle.paused || lifecycle.queue.length === 0) return lifecycle;
  const bodyId = lifecycle.queue[0];
  const record = lifecycle.records[bodyId];
  if (!record || record.status !== 'queued') {
    return updateLifecycle(lifecycle, { queue: lifecycle.queue.slice(1) }, nowIso);
  }
  return updateLifecycle(lifecycle, {
    queue: lifecycle.queue.slice(1),
    activeBodyId: bodyId,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: 'generating',
        startedAt: nowIso,
        failureReason: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function resumeBodyGenerationQueue(
  lifecycle: BodyGenerationLifecycle,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  return updateLifecycle(lifecycle, { paused: false }, nowIso);
}

export function pauseBodyGenerationQueue(
  lifecycle: BodyGenerationLifecycle,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  return updateLifecycle(lifecycle, { paused: true }, nowIso);
}

export function removeQueuedBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record || record.status !== 'queued') return lifecycle;
  return updateLifecycle(lifecycle, {
    queue: lifecycle.queue.filter((candidate) => candidate !== bodyId),
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: fallbackReadyStatus(record),
        requestedAt: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function cancelActiveBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record || lifecycle.activeBodyId !== bodyId || record.status !== 'generating') return lifecycle;
  return updateLifecycle(lifecycle, {
    activeBodyId: null,
    paused: true,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: fallbackReadyStatus(record),
        startedAt: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function failBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  failureReason: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record) return lifecycle;
  return updateLifecycle(lifecycle, {
    activeBodyId: lifecycle.activeBodyId === bodyId ? null : lifecycle.activeBodyId,
    paused: true,
    records: {
      ...lifecycle.records,
      [bodyId]: {
        ...record,
        status: 'failed',
        failureReason,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function completeBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  artifact: AirlessRockyBodyArtifact,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[artifact.bodyId];
  if (!record) return lifecycle;
  return updateLifecycle(lifecycle, {
    activeBodyId: lifecycle.activeBodyId === artifact.bodyId ? null : lifecycle.activeBodyId,
    records: {
      ...lifecycle.records,
      [artifact.bodyId]: {
        ...record,
        status: 'generated',
        workflow: {
          id: artifact.workflow.id,
          version: artifact.workflow.version,
          graphSignature: artifact.workflow.graphSignature
        },
        sourceBodySignature: artifact.source.sourceSignature,
        artifactKeys: [...new Set([...record.artifactKeys, artifact.artifactKey])],
        completedAt: artifact.completedAt,
        failureReason: undefined,
        staleReason: undefined,
        updatedAt: nowIso
      }
    }
  }, nowIso);
}

export function retryBodyGeneration(
  lifecycle: BodyGenerationLifecycle,
  bodyId: string,
  nowIso = new Date().toISOString()
): BodyGenerationLifecycle {
  const record = lifecycle.records[bodyId];
  if (!record || (record.status !== 'failed' && record.status !== 'stale')) return lifecycle;
  return queueBodyGeneration(lifecycle, bodyId, record.requestedFidelity, nowIso);
}

export function airlessArtifactForBody(
  project: WorldProject,
  orbitalContext: SystemOrbitalContextArtifact,
  bodyId: string,
  requestedFidelity: BodyGenerationFidelity = 'preview'
): AirlessRockyBodyArtifact | null {
  try {
    const source = airlessRockyBodySourceFromProject(project, orbitalContext, bodyId, requestedFidelity);
    const artifact = project.enrichmentArtifacts?.[airlessRockyBodyArtifactKey(bodyId)];
    return isCurrentAirlessRockyBodyArtifact(source, artifact) ? artifact : null;
  } catch {
    return null;
  }
}

function reconcileRecord(input: {
  existing: BodyGenerationRecord | undefined;
  bodyId: string;
  parentBodyId: string | null;
  status: BodyGenerationLifecycleStatus;
  eligible: boolean;
  eligibilityReason: string;
  profile: BodyGenerationRecord['profile'];
  stableSeed: string;
  sourceBodySignature: string;
  requestedFidelity?: BodyGenerationFidelity;
  nowIso: string;
  artifactKey?: string;
  completedAt?: string;
  staleReason?: string;
}): BodyGenerationRecord {
  const existing = input.existing;
  const sourceChanged = Boolean(existing && existing.sourceBodySignature !== input.sourceBodySignature);
  const preservedStatus = existing && !sourceChanged && input.eligible
    && ['queued', 'generating', 'failed'].includes(existing.status)
    ? existing.status
    : input.status;
  const artifactKeys = input.artifactKey
    ? [...new Set([...(existing?.artifactKeys ?? []), input.artifactKey])]
    : existing?.artifactKeys ?? [];
  return {
    bodyId: input.bodyId,
    parentBodyId: input.parentBodyId,
    status: sourceChanged && existing?.status === 'generated' ? 'stale' : preservedStatus,
    eligible: input.eligible,
    eligibilityReason: input.eligibilityReason,
    profile: input.profile,
    stableSeed: input.stableSeed,
    requestedFidelity: input.requestedFidelity ?? existing?.requestedFidelity ?? 'preview',
    workflow: {
      id: input.profile ? AIRLESS_ROCKY_BODY_WORKFLOW_ID : existing?.workflow.id ?? '',
      version: input.profile ? AIRLESS_ROCKY_BODY_WORKFLOW_VERSION : existing?.workflow.version ?? '',
      graphSignature: input.profile ? airlessRockyBodyGraphSignature() : existing?.workflow.graphSignature
    },
    sourceBodySignature: input.sourceBodySignature,
    artifactKeys,
    requestedAt: preservedStatus === 'queued' || preservedStatus === 'generating' ? existing?.requestedAt : undefined,
    startedAt: preservedStatus === 'generating' ? existing?.startedAt : undefined,
    completedAt: input.status === 'generated' ? input.completedAt ?? existing?.completedAt : undefined,
    updatedAt: existing?.updatedAt ?? input.nowIso,
    staleReason: sourceChanged ? 'Body scaffold or orbital source changed after generation.' : input.staleReason,
    failureReason: preservedStatus === 'failed' ? existing?.failureReason : undefined
  };
}

function fallbackReadyStatus(record: BodyGenerationRecord): BodyGenerationLifecycleStatus {
  if (record.artifactKeys.length > 0) return 'generated';
  return record.eligible ? 'ready' : 'placeholder';
}

function updateLifecycle(
  lifecycle: BodyGenerationLifecycle,
  changes: Partial<BodyGenerationLifecycle>,
  nowIso: string
): BodyGenerationLifecycle {
  return {
    ...lifecycle,
    ...changes,
    updatedAt: nowIso
  };
}

function lifecycleEquals(left: BodyGenerationLifecycle | undefined, right: BodyGenerationLifecycle): boolean {
  if (!left) return false;
  return JSON.stringify(left) === JSON.stringify(right);
}

function stableSignature(value: unknown): string {
  const serialized = stableStringify(value);
  let hash = 2166136261;
  for (let index = 0; index < serialized.length; index += 1) {
    hash ^= serialized.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return `fnv1a-${(hash >>> 0).toString(16).padStart(8, '0')}`;
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(record[key])}`).join(',')}}`;
  }
  return JSON.stringify(value);
}
